return {
	host = "127.0.0.1",
	port = 28081,
	auth_path = "userdata/ai_auth.lua",
	usage_db_path = "userdata/ai_proxy_usage.db",
	-- User-provided reference prices, USD per million tokens; omitted prices cost 0.
	model_prices = {
		["gpt-6-astra"] = {input = 10, cached_input = 1, output = 50},
		["gpt-6-sol"] = {input = 2, cached_input = 0.2, output = 10},
		["gpt-6-luna"] = {input = 0.1, cached_input = 0.01, output = 0.5},
		["gpt-5.6-sol"] = {input = 4, cached_input = 0.4, output = 20},
		["gpt-5.6-terra"] = {input = 2, cached_input = 0.2, output = 12},
		["gpt-5.6-luna"] = {input = 0.2, cached_input = 0.02, output = 1.2},
		["gpt-5.5"] = {input = 5, cached_input = 0.5, output = 30},
		["gpt-5.4"] = {input = 2.5, cached_input = 0.25, output = 15},
		["gpt-5.4-mini"] = {input = 0.75, cached_input = 0.075, output = 4.5},
	},
	network_path = "userdata/network.lua",
	models = {
		"gpt-6-astra",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.4-mini",
		"gpt-5.3-codex-spark",
	},
	-- Map public model names to different upstream models, for example:
	-- ["gpt-5.6-sol"] = "gpt-5.6-terra",
	model_redirects = {},
	reasoning_effort = "medium",
	verbosity = "low",
	upstream_timeout = 300,
	client_timeout = 300,
	max_body_size = 16 * 1024 * 1024,
	max_response_size = 4 * 1024 * 1024,
	max_clients = 64,
	max_concurrent_requests_per_user = 4,
	max_requests_per_minute = 120,
	users = {
		{name = "local", access_token = "replace-with-a-long-random-token"},
	},
}
